services:
  - type: web
    name: petmet
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: PetMet.settings
      - key: PORT
        value: 8000
